# Generated by Django 5.0.6 on 2024-06-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursemodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('yearofstudy', models.IntegerField(max_length=13)),
                ('modulename', models.CharField(max_length=255)),
                ('modulecode', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('choice_1', models.TextField(max_length=1000)),
                ('choice_2', models.TextField(max_length=1000)),
                ('choice_3', models.TextField(max_length=1000)),
                ('choice_4', models.TextField(max_length=1000)),
                ('choice_5', models.TextField(max_length=1000)),
                ('choice_6', models.TextField(max_length=1000)),
                ('wrong_7', models.TextField(max_length=1000)),
                ('wrong_8', models.TextField(max_length=1000)),
                ('wrong_9', models.TextField(max_length=1000)),
                ('wrong_10', models.TextField(max_length=1000)),
                ('modulecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.coursemodule')),
            ],
        ),
    ]
