# Generated by Django 5.0.6 on 2024-06-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='yearofstudy',
            field=models.IntegerField(),
        ),
    ]
