# Generated by Django 5.0.6 on 2024-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_coursemodule_yearofstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choice_1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice_2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice_3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice_4',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice_5',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice_6',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='wrong_10',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='wrong_7',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='wrong_8',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='wrong_9',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
